language: node_js
node_js:
  - node
  - lts/*
branches:
  only:
    - master
env:
  matrix:
    - TRAVIS=true
cache:
  yarn: true
  directories:
    - node_modules
script:
  - yarn lint
  - yarn test
after_script:
  - npx codecov
notifications:
  email: false
